/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    APDetails: typeof import('./src/components/ApplyDeveloper/APDetails.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Footer: typeof import('./src/components/HeaderFooter/Footer.vue')['default']
    Header: typeof import('./src/components/HeaderFooter/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainContainer: typeof import('./src/components/MainContainer/MainContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu/SideMenu.vue')['default']
    SideMenuUserCard: typeof import('./src/components/SideMenu/SideMenuUserCard/SideMenuUserCard.vue')['default']
    SogouInputThemeContainer: typeof import('./src/components/SogouInputTheme/SogouInputThemeContainer.vue')['default']
    SogouInputThemeHeader: typeof import('./src/components/SogouInputTheme/SogouInputThemeHeader.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopHeader: typeof import('./src/components/HeaderFooter/TopHeader.vue')['default']
    UserBanner: typeof import('./src/components/PersonCenter/UserBanner.vue')['default']
    UserForm: typeof import('./src/components/PersonCenter/UserForm.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
